// Auto-generated by scripts/sync-abi.ts — update with real addresses at deploy time (M11).
export const addresses = {
  monadTestnet: {
    factory: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    reputation: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    mockStable: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
} as const;
